// Fetches transcript via MAIN world (which uses ANDROID innertube client)
// The MAIN world runs on youtube.com origin, avoiding CORS and POT issues

window.YTBlog = window.YTBlog || {};

window.YTBlog.fetchTranscript = async function(captionTracks, videoId, languageCode) {
  if ((!captionTracks || captionTracks.length === 0) && !videoId) {
    throw new Error('NO_CAPTIONS');
  }

  const lang = languageCode || 'en';

  // Find matching track — manual preferred over auto-generated
  const manual = captionTracks?.find(t => t.kind !== 'asr' && t.languageCode === lang);
  const autoLang = captionTracks?.find(t => t.languageCode === lang);
  const manualEn = captionTracks?.find(t => t.kind !== 'asr' && t.languageCode === 'en');
  const autoEn = captionTracks?.find(t => t.languageCode === 'en');
  const track = manual || autoLang || manualEn || autoEn;
  if (!track) throw new Error('NO_CAPTIONS');
  const isAutoGenerated = track.kind === 'asr';
  const resolvedLang = track.languageCode;

  const vid = videoId || new URLSearchParams(location.search).get('v');
  const requestId = Math.random().toString(36).slice(2);

  const segments = await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      window.removeEventListener('message', handler);
      reject(new Error('Transcript fetch timed out'));
    }, 15000);

    function handler(event) {
      if (event.source !== window) return;
      if (event.data?.type !== 'YTBLOG_TRANSCRIPT_RESULT') return;
      if (event.data.requestId !== requestId) return;

      window.removeEventListener('message', handler);
      clearTimeout(timeout);

      if (event.data.success) {
        resolve(event.data.segments);
      } else {
        reject(new Error(event.data.error || 'Transcript fetch failed'));
      }
    }

    window.addEventListener('message', handler);
    window.postMessage({
      type: 'YTBLOG_FETCH_TRANSCRIPT',
      videoId: vid,
      languageCode: resolvedLang,
      requestId,
    }, window.location.origin);
  });

  if (!segments || segments.length === 0) {
    throw new Error('NO_CAPTIONS');
  }

  console.log('[YTBlog] Got', segments.length, 'transcript segments (lang:', resolvedLang + ')');
  return { segments, isAutoGenerated, language: resolvedLang };
};
